//### Indicate a new Call

###Get Service: Collection
http://localhost:4004/odata/v4/ExpensesColl

###Get Service: MetaData of collection
http://localhost:4004/odata/v4/ExpensesColl/$metadata


###Get Service: User Set
http://localhost:4004/odata/v4/ExpensesColl/UserSet


###Get Service: User Set: Pagination 
http://localhost:4004/odata/v4/ExpensesColl/UserSet?$top=2&$skip=2

###Get Service: User Set: Count 
http://localhost:4004/odata/v4/ExpensesColl/UserSet/$count

###Get Service: User Set: Single Record by Key
http://localhost:4004/odata/v4/ExpensesColl/UserSet/1


###Get Service: User Set: Filter 
http://localhost:4004/odata/v4/ExpensesColl/UserSet?$filter=modifiedBy eq 'admin'

###Get Service: User Set: Case Filter  
http://localhost:4004/odata/v4/ExpensesColl/UserSet?$filter=contains(modifiedBy, 'admin')


###POST Service: User Set   ===> Not working
http://localhost:4004/odata/v4/ExpensesColl/UserSet
Content-Type: application/json

{
      "UserID": "106",
      "FirstName":"Dev",
      "LastName": "Singh",
      "Email": "d@example.com"
}

###Get the data of new User Set - COPY THE ID FROM LAST CALL MANUALLY
http://localhost:4004/odata/v4/ExpensesColl/UserSet/5

###PATCH - used to update data
PATCH http://localhost:4004/odata/v4/ExpensesColl/UserSet/5
Content-Type: application/json

{
    "FirstName": "Consultant"
}


###DELETE - Remove data from DB
DELETE http://localhost:4004/odata/v4/ExpensesColl/UserSet/5

###Test the V2 response :: npm install @cap-js-community/odata-v2-adapter
http://localhost:4004/odata/v2/ExpensesColl/UserSet/3

####Lazy loading concept 
http://localhost:4004/odata/v2/ExpensesColl/UserSet('3')/Items_Categories


###Calling the action :: Not working
POST http://localhost:4004/odata/v4/ExpensesColl/UserSet/penalty
Content-Type: application/json

{
  "UserID": "106"  
}

###Call the function
http://localhost:4004/odata/v4/ExpensesColl/loadInitials()

